adding always

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -54,12 +54,13 @@ jobs:
       id: test_step
       run: |
         pipenv run pytest tests/test_home.py -n=3 --browser=chrome --headless -v -s --dashboard --html=report/report.html
-      continue-on-error: true
+#      continue-on-error: true
     - name: upload-artifacts
+      if: always()
       uses: actions/upload-artifact@v4
       with:
         name: my-artifact
         path: report/
-    - name: Fail job if tests failed
-      if: steps.test_step.outcome == 'failure'
-      run: exit 1
+#    - name: Fail job if tests failed
+#      if: steps.test_step.outcome == 'failure'
+#      run: exit 1
